netty:
  port: 8000

business:
  thread:
    count: 100
proxy:
  registry:
    address: zookeeper://10.0.0.28:2181
    group: dubbo
  metadata-report:
    address: zookeeper://10.0.0.28:2181

mapping:
  services:
    - name: demoservice
      interfaze: org.apache.dubbo.api.DemoService
      group: test
      version: 1.0.0